/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.5
 * Generated at: 2018-04-27 02:57:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class driver_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Hitch: Driver</title>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Khand\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <header>\r\n");
      out.write("    <img src=\"images/hitch.png\" id=\"logo\">\r\n");
      out.write("    <h1 class=\"myheader\">HITCH</h1>\r\n");
      out.write("      \r\n");
      out.write("    <nav id=\"navmenu\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li id=\"nav-home\"><a href=\"main.jsp\">Home</a></li>\r\n");
      out.write("        <li id=\"nav-ride\"><a href=\"ride.jsp\">Ride</a></li>\r\n");
      out.write("        <li id=\"nav-profile\"><a href=\"profile.jsp\">Profile</a></li>\r\n");
      out.write("        <li id=\"nav-delivery\"><a href=\"delivery.jsp\">Delivery</a></li>\r\n");
      out.write("        <li id=\"nav-driver\"><a href=\"driver.jsp\">Driver</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </header>\r\n");
      out.write("  <img class=\"services\" src=\"images/driver.png\">\r\n");
      out.write("  <h1 class=\"request\">Driver</h1>\r\n");
      out.write("  <form class=\"driver\" name=\"driver\" action=\"/hitchwebapp/driver.do\" method=\"POST\" autocomplete=\"on\" oninput=\"output.value\">\r\n");
      out.write("    <input type=\"text\" id=\"fname\" name=\"fname\" placeholder=\"First Name\" required />\r\n");
      out.write("    <p>\r\n");
      out.write("    <input type=\"text\" id=\"lname\" name=\"lname\" placeholder=\"Last Name\" required />\r\n");
      out.write("    </p>\r\n");
      out.write("    <p>\r\n");
      out.write("    <input type=\"text\" id=\"setaddress\" name=\"setaddress\" placeholder=\"Enter set street address\" required />\r\n");
      out.write("    </p>\r\n");
      out.write("    <p>\r\n");
      out.write("    <input type=\"text\" id=\"setcity\" name=\"setcity\" placeholder=\"Enter set city\" required />\r\n");
      out.write("    </p>\r\n");
      out.write("    <p>\r\n");
      out.write("        <label>Set State:</label>\r\n");
      out.write("        <select name=\"setstate\">\r\n");
      out.write("\t\t\t<option value=\"AL\">AL</option>\r\n");
      out.write("\t\t\t<option value=\"AK\">AK</option>\r\n");
      out.write("\t\t\t<option value=\"AR\">AR</option>\t\r\n");
      out.write("\t\t\t<option value=\"AZ\">AZ</option>\r\n");
      out.write("\t\t\t<option value=\"CA\">CA</option>\r\n");
      out.write("\t\t\t<option value=\"CO\">CO</option>\r\n");
      out.write("\t\t\t<option value=\"CT\">CT</option>\r\n");
      out.write("\t\t\t<option value=\"DC\">DC</option>\r\n");
      out.write("\t\t\t<option value=\"DE\">DE</option>\r\n");
      out.write("\t\t\t<option value=\"FL\">FL</option>\r\n");
      out.write("\t\t\t<option value=\"GA\">GA</option>\r\n");
      out.write("\t\t\t<option value=\"HI\">HI</option>\r\n");
      out.write("\t\t\t<option value=\"IA\">IA</option>\t\r\n");
      out.write("\t\t\t<option value=\"ID\">ID</option>\r\n");
      out.write("\t\t\t<option value=\"IL\">IL</option>\r\n");
      out.write("\t\t\t<option value=\"IN\">IN</option>\r\n");
      out.write("\t\t\t<option value=\"KS\">KS</option>\r\n");
      out.write("\t\t\t<option value=\"KY\">KY</option>\r\n");
      out.write("\t\t\t<option value=\"LA\">LA</option>\r\n");
      out.write("\t\t\t<option value=\"MA\">MA</option>\r\n");
      out.write("\t\t\t<option value=\"MD\">MD</option>\r\n");
      out.write("\t\t\t<option value=\"ME\">ME</option>\r\n");
      out.write("\t\t\t<option value=\"MI\">MI</option>\r\n");
      out.write("\t\t\t<option value=\"MN\">MN</option>\r\n");
      out.write("\t\t\t<option value=\"MO\">MO</option>\t\r\n");
      out.write("\t\t\t<option value=\"MS\">MS</option>\r\n");
      out.write("\t\t\t<option value=\"MT\">MT</option>\r\n");
      out.write("\t\t\t<option value=\"NC\">NC</option>\t\r\n");
      out.write("\t\t\t<option value=\"NE\">NE</option>\r\n");
      out.write("\t\t\t<option value=\"NH\">NH</option>\r\n");
      out.write("\t\t\t<option value=\"NJ\">NJ</option>\r\n");
      out.write("\t\t\t<option value=\"NM\">NM</option>\t\t\t\r\n");
      out.write("\t\t\t<option value=\"NV\">NV</option>\r\n");
      out.write("\t\t\t<option value=\"NY\">NY</option>\r\n");
      out.write("\t\t\t<option value=\"ND\">ND</option>\r\n");
      out.write("\t\t\t<option value=\"OH\">OH</option>\r\n");
      out.write("\t\t\t<option value=\"OK\">OK</option>\r\n");
      out.write("\t\t\t<option value=\"OR\">OR</option>\r\n");
      out.write("\t\t\t<option value=\"PA\">PA</option>\r\n");
      out.write("\t\t\t<option value=\"RI\">RI</option>\r\n");
      out.write("\t\t\t<option value=\"SC\">SC</option>\r\n");
      out.write("\t\t\t<option value=\"SD\">SD</option>\r\n");
      out.write("\t\t\t<option value=\"TN\">TN</option>\r\n");
      out.write("\t\t\t<option value=\"TX\">TX</option>\r\n");
      out.write("\t\t\t<option value=\"UT\">UT</option>\r\n");
      out.write("\t\t\t<option value=\"VT\">VT</option>\r\n");
      out.write("\t\t\t<option value=\"VA\">VA</option>\r\n");
      out.write("\t\t\t<option value=\"WA\">WA</option>\r\n");
      out.write("\t\t\t<option value=\"WI\">WI</option>\t\r\n");
      out.write("\t\t\t<option value=\"WV\">WV</option>\r\n");
      out.write("\t\t\t<option value=\"WY\">WY</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("    <p>\r\n");
      out.write("\t<input type=\"submit\" id=\"submit\" value=\"Set Location\" onclick=\"validate();\" />\r\n");
      out.write("\t</p>\r\n");
      out.write("  </form>\r\n");
      out.write("  <p></p><p></p>\r\n");
      out.write("  <form class=\"getrequests\" action=\"/action_page.php\" method=\"get\">\r\n");
      out.write("  \t<p>\r\n");
      out.write("  \t<textarea id=\"custrequest\" name=\"custrequest\" form=\"requests\" rows=\"4\" cols=\"50\"></textarea>\r\n");
      out.write("  \t</p>\r\n");
      out.write("  \t<p>\r\n");
      out.write("\t<input type=\"submit\" id=\"submit\" value=\"Get Current Requests\" onclick=\"\" />\r\n");
      out.write("\t</p>\r\n");
      out.write("  </form>\r\n");
      out.write("  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\r\n");
      out.write("  <script  src=\"js/index.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
