Vagrant.configure("2") do |config|
  # Use specified vagrant box
  config.vm.box = "ubuntu/xenial64"
  # Pass over deploy key for git repository
  config.vm.provision "file", source: "../deploy", destination: "~/.ssh/id_rsa"
  # After box is launched, run the below script
  config.vm.provision :shell, path: "appsetup.sh"
  # Pass over firebase key now that git repository has been cloned 
  # config.vm.provision "file", source: "../ServiceAccount.json", destination: "/home/vagrant/2019-team-04r/q_app/"
  # Open below port access for Node/Express
  config.vm.network "forwarded_port", guest: 5000, host: 5000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 9005, host: 9005, host_ip: "127.0.0.1"
end
